KNOWN_PORTS = {
    21: "FTP: 암호화되지 않은 파일 전송 (해킹 취약)",
    22: "SSH: 원격 접속 서비스",
    23: "Telnet: 암호화되지 않은 원격 접속 (매우 위험)",
    25: "SMTP: 메일 전송 프로토콜",
    53: "DNS: 도메인 이름 해석 서비스 (증폭 공격 주의)",
    80: "HTTP: 웹 서비스 (비암호화)",
    443: "HTTPS: 보안 웹 서비스",
    1433: "MSSQL: Microsoft SQL Server 데이터베이스",
    1521: "Oracle: Oracle 데이터베이스",
    3306: "MySQL: MySQL/MariaDB 데이터베이스",
    5432: "PostgreSQL: PostgreSQL 데이터베이스",
    6379: "Redis: 인메모리 데이터 저장소",
    8080: "HTTP-Proxy: 대체 웹 포트 (개발용/프록시)",
    9000: "FastCGI: PHP-FPM 등 어플리케이션 인터페이스",
    11211: "Memcached: 분산 메모리 캐싱 시스템",
    27017: "MongoDB: NoSQL 데이터베이스",
    3389: "RDP: Windows 원격 데스크톱 접속",
}