---
common_packages:
  - git
  - firewalld
  - python3
  - python3-pip
  - python3-devel
  - gcc
  - make
  - wget
  - tar
  - openssl-devel
  - bzip2-devel
  - libffi-devel
  - zlib-devel
  - xz-devel
  - readline-devel
  - sqlite-devel
  - tk-devel

nginx_listen_port: 80

nginx_upstreams:
  - path: /monitor
    host: 127.0.0.1
    port: 8000
  - path: /other
    host: 127.0.0.1
    port: 9000

# MongoDB 인증 활성화 여부
mongodb_auth_enabled: true

# 앱이 접근할 DB 이름
mongodb_app_database: process_monitor

# 비밀번호는 vault로 분리
mongodb_admin_username: admin
mongodb_app_username: app_user

# server-monitor 전용 Python 3.13 설정
python313_version: "3.13.3"
python313_prefix: "/usr/local"
python313_bin: "/usr/local/bin/python3.13"